<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CPF_lumSaude_cpf1</name>
   <tag></tag>
   <elementGuidId>187b5f39-3686-47c0-b100-ed3ed5ed38d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lumSaude_cpf1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lumSaude_cpf1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;CPF&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>508d2bce-12e7-4a95-afe7-ef230d2046d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>51cdc7f1-cf0a-44ef-8128-04822fbc0516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lumSaude_cpf1</value>
      <webElementGuid>63670e92-9da4-4a2d-a029-964c1d964d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lumSaude_cpf1</value>
      <webElementGuid>bfbbcef5-9ac2-474a-a38d-4bb7ede878e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control code14 lumSaude_jumpNext</value>
      <webElementGuid>3b1d33b0-5eca-46cf-88fb-3d2534b0a6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>c70676e4-d63d-449f-ad0c-06e30b28a650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4f2634a2-4c79-49f4-8846-5939093c2b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lumSaude_cpf1&quot;)</value>
      <webElementGuid>88004438-913c-4d8e-b176-be5f9ff84b98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lumSaude_cpf1']</value>
      <webElementGuid>0d1bb602-5a26-4a9b-b72a-f1c38fe5491d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form_8A6164A961DEAA7F0161DEBB127E630D']/div/div/div/div/div/div/input</value>
      <webElementGuid>22e50489-d585-4681-bc93-b82182c3cb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/input</value>
      <webElementGuid>c31dcff2-0d14-43b2-8902-8b227af700f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'lumSaude_cpf1' and @name = 'lumSaude_cpf1']</value>
      <webElementGuid>22287c42-10d9-4a4c-b7e0-207011f60e18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
